---
# tasks file for proxmox

- name: check if Proxmox repo exists
  stat:
    path: /etc/apt/sources.list.d/pve-install-repo.list
  register: pve_repo

- name: check if Proxmox key exists
  stat:
    path: /etc/apt/trusted.gpg.d/proxmox-ve-release-6.x.gpg
  register: pve_key

- name: Add Proxmox VE repo
  shell: echo "deb http://download.proxmox.com/debian/pve buster pve-no-subscription" > /etc/apt/sources.list.d/pve-install-repo.list
  when: not pve_repo.stat.exists

- name: Add Proxmox VE repo key
  get_url:
    url: http://download.proxmox.com/debian/proxmox-ve-release-6.x.gpg
    dest: /etc/apt/trusted.gpg.d/proxmox-ve-release-6.x.gpg
  when: not pve_key.stat.exists

- name: apt update
  apt:
    update_cache: yes

- name: apt full-upgrade
  apt:
    upgrade: full

- name: postfix install pre-seed hostname
  debconf:
    name: postfix
    question: postfix/mailname
    value: "{{ ansible_hostname }}"
    vtype: string

- name: postfix install pre-seed mailer type
  debconf:
    name: postfix
    question: postfix/main_mailer_type
    value: "Local only"
    vtype: string

- name: Install packages
  apt:
    pkg: "{{ packages }}"
    update_cache: true
    cache_valid_time: 300
  notify: Reboot host

- name: Remove Proxmox PVE Enterprise repo if exists
  file:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent