---
# tasks file for host_prep

- name: Change the hostname
  hostname:
    name: '{{ proxmox_fqdn }}'

- name: Add public IP to /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: '{{ ansible_default_ipv4.address }} {{ proxmox_fqdn }} {{ proxmox_hostname }}'
    state: present
    create: yes

- name: Install openvswitch packages
  apt:
    pkg: "{{ packages }}"
    update_cache: true
    cache_valid_time: 300

- name: Apply network template for OpenVSwitch networking
  template:
    src: "interfaces"
    dest: /etc/network/interfaces

- name: Set permissions on /etc/network/interfaces
  file:
    path: /etc/network/interfaces
    mode: '644'